cat > ansible/inventory.ini <<EOF
[web]
${INSTANCE_ID}

[web:vars]
ansible_connection=amazon.aws.aws_ssm_connection
ansible_aws_ssm_region=us-east-1
ansible_user=ubuntu
ansible_python_interpreter=/usr/bin/python3
EOF