- name: Production Deployment (SSM + Docker)
  hosts: web
  become: false
  gather_facts: true

  vars:
    repo_url: "https://github.com/Demystifier-git/Minishop-deployed-on-Ec2.git"
    repo_branch: "main"
    app_dir: "/opt/minishop"

  tasks:

    # =========================================================
    # VERIFY DOCKER EXISTS
    # =========================================================
    - name: Check Docker
      command: docker --version
      register: docker_check
      changed_when: false

    # =========================================================
    # CREATE APP DIR
    # =========================================================
    - name: Create app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'

    # =========================================================
    # CLONE REPO
    # =========================================================
    - name: Clone repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: "{{ repo_branch }}"
        force: yes
