# .github/workflows/deploy-prod.yml

name: Deploy Production

on:
  workflow_dispatch:
    inputs:
      service:
        description: Service to deploy
        required: true
        type: choice
        options:
          - backend
          - frontend
          - all

      version:
        description: Docker image tag (example: v1.0.0)
        required: true
        type: string

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 387041334219.dkr.ecr.us-east-1.amazonaws.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to EC2 (SSM)
        env:
          SERVICE: ${{ github.event.inputs.service }}
          VERSION: ${{ github.event.inputs.version }}
          INSTANCE_ID: ${{ secrets.PROD_INSTANCE_ID }}
          ECR_REGISTRY: ${{ env.ECR_REGISTRY }}

        run: |

          if [ "$SERVICE" = "backend" ]; then

            COMMANDS='[
              "set -e",
              "cd /app/Minishop-deployed-on-Ec2",
              "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin '"$ECR_REGISTRY"'",
              "docker pull '"$ECR_REGISTRY"'/minishop-backend:'"$VERSION"'",
              "docker compose up -d backend"
            ]'

          elif [ "$SERVICE" = "frontend" ]; then

            COMMANDS='[
              "set -e",
              "cd /app/Minishop-deployed-on-Ec2",
              "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin '"$ECR_REGISTRY"'",
              "docker pull '"$ECR_REGISTRY"'/minishop-frontend:'"$VERSION"'",
              "docker compose up -d frontend"
            ]'

          else

            COMMANDS='[
              "set -e",
              "cd /app/Minishop-deployed-on-Ec2",
              "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin '"$ECR_REGISTRY"'",
              "docker pull '"$ECR_REGISTRY"'/minishop-backend:'"$VERSION"'",
              "docker pull '"$ECR_REGISTRY"'/minishop-frontend:'"$VERSION"'",
              "docker compose up -d"
            ]'

          fi

          aws ssm send-command \
            --instance-ids "$PROD_INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --parameters commands="$COMMANDS"